var examples = {
    initExample0: function(){
        $('#bar00').addClass('selected');   
        $('#bar07').addClass('selected');
        $('#bar12').addClass('selected');   
        $('#bar16').addClass('selected');
        $('#bar20').addClass('selected');   
        $('#bar21').addClass('selected');
        $('#bar24').addClass('selected');   
        $('#bar25').addClass('selected');
        $('#bar40').addClass('selected');   
        $('#bar42').addClass('selected');
        $('#bar44').addClass('selected');   
        $('#bar46').addClass('selected');
    },
    initExample1: function(){
        $('#bar10').addClass('selected');   
        $('#bar13').addClass('selected');  
        $('#bar20').addClass('selected');   
        $('#bar22').addClass('selected');
        $('#bar24').addClass('selected');   
        $('#bar26').addClass('selected');
        $('#bar42').addClass('selected');   
        $('#bar47').addClass('selected');
        $('#bar51').addClass('selected');   
        $('#bar55').addClass('selected');
        $('#bar60').addClass('selected');   
        $('#bar62').addClass('selected');
        $('#bar64').addClass('selected');   
        $('#bar66').addClass('selected');
        $('#bar74').addClass('selected');   
    },
    initExample2: function(){
        $('#bar05').addClass('selected');   
        $('#bar16').addClass('selected'); 
        $('#bar23').addClass('selected');   
        $('#bar30').addClass('selected'); 
        $('#bar34').addClass('selected');   
        $('#bar52').addClass('selected'); 
        $('#bar56').addClass('selected'); 
        $('#bar61').addClass('selected'); 
        $('#bar63').addClass('selected'); 
        $('#bar67').addClass('selected'); 
    }, 
    initExample3: function(){
        $('#bar00').addClass('selected');   
        $('#bar01').addClass('selected'); 
        $('#bar02').addClass('selected');   
        $('#bar03').addClass('selected'); 
        $('#bar04').addClass('selected');   
        $('#bar05').addClass('selected'); 
        $('#bar06').addClass('selected');   
        $('#bar07').addClass('selected'); 
        $('#bar16').addClass('selected');   
        $('#bar17').addClass('selected'); 
        $('#bar24').addClass('selected');   
        $('#bar25').addClass('selected'); 
        $('#bar26').addClass('selected');   
        $('#bar27').addClass('selected'); 
        $('#bar34').addClass('selected');   
        $('#bar36').addClass('selected'); 
        $('#bar45').addClass('selected');   
        $('#bar47').addClass('selected'); 
        $('#bar53').addClass('selected'); 
        $('#bar60').addClass('selected');   
        $('#bar62').addClass('selected'); 
        $('#bar64').addClass('selected');   
        $('#bar66').addClass('selected'); 
        $('#bar71').addClass('selected');   
        $('#bar73').addClass('selected'); 
        $('#bar75').addClass('selected');   
        $('#bar77').addClass('selected'); 
    }, 
    initExample4: function(){
        $('#bar00').addClass('selected');   
        $('#bar01').addClass('selected'); 
        $('#bar02').addClass('selected');   
        $('#bar03').addClass('selected'); 
        $('#bar04').addClass('selected');   
        $('#bar05').addClass('selected'); 
        $('#bar06').addClass('selected');   
        $('#bar07').addClass('selected');   
        $('#bar10').addClass('selected');   
        $('#bar11').addClass('selected'); 
        $('#bar12').addClass('selected');   
        $('#bar13').addClass('selected'); 
        $('#bar14').addClass('selected');   
        $('#bar15').addClass('selected'); 
        $('#bar26').addClass('selected'); 
        $('#bar30').addClass('selected');   
        $('#bar31').addClass('selected'); 
        $('#bar32').addClass('selected');   
        $('#bar33').addClass('selected'); 
        $('#bar34').addClass('selected');   
        $('#bar35').addClass('selected'); 
        $('#bar36').addClass('selected');   
        $('#bar37').addClass('selected');
        $('#bar40').addClass('selected');   
        $('#bar44').addClass('selected'); 
        $('#bar53').addClass('selected');   
        $('#bar63').addClass('selected'); 
        $('#bar67').addClass('selected');   
        $('#bar77').addClass('selected'); 
    },
    initExample5: function(){
        $('#bar00').addClass('selected');   
        $('#bar02').addClass('selected');   
        $('#bar04').addClass('selected');   
        $('#bar06').addClass('selected'); 
        $('#bar11').addClass('selected');   
        $('#bar13').addClass('selected');   
        $('#bar15').addClass('selected');   
        $('#bar17').addClass('selected'); 
        $('#bar20').addClass('selected');   
        $('#bar21').addClass('selected');   
        $('#bar22').addClass('selected');   
        $('#bar23').addClass('selected'); 
        $('#bar24').addClass('selected');   
        $('#bar25').addClass('selected');   
        $('#bar26').addClass('selected');   
        $('#bar27').addClass('selected'); 
        $('#bar30').addClass('selected');   
        $('#bar31').addClass('selected');   
        $('#bar32').addClass('selected');   
        $('#bar33').addClass('selected'); 
        $('#bar34').addClass('selected');   
        $('#bar35').addClass('selected');   
        $('#bar36').addClass('selected');   
        $('#bar37').addClass('selected');
        $('#bar44').addClass('selected');   
        $('#bar46').addClass('selected');
        $('#bar50').addClass('selected');   
        $('#bar64').addClass('selected');
        $('#bar65').addClass('selected');
        $('#bar66').addClass('selected');
        $('#bar67').addClass('selected');
        $('#bar70').addClass('selected');   
        $('#bar72').addClass('selected');   
        $('#bar74').addClass('selected');   
        $('#bar76').addClass('selected'); 
    }, 
    clearAll: function(){
        $('.bar').removeClass('selected');
    }
    
}